import 'package:firebase_core/firebase_core.dart';
import 'package:workmanager/workmanager.dart';
import 'core/services/background_service.dart';
import 'core/services/notification_service.dart';
import 'firebase_options.dart'; // Will be generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Note: user needs to run `flutterfire configure` to generate firebase_options.dart
  // For now we'll comment out the options part or assume it exists/will exist.
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp(); 

  await NotificationService.initialize();
  
  await Workmanager().initialize(
    callbackDispatcher,
    isInDebugMode: false,
  );
  
  await Workmanager().registerPeriodicTask(
    "1",
    taskName,
    frequency: const Duration(minutes: 15),
  );

  runApp(
    const ProviderScope(
      child: AquaLevelApp(),
    ),
  );
}
